# This is a configuration file for Dependabot version updates.
# It specifies which package ecosystems to update and where the package manifests are located.
# For more information, see: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # Update Python packages using pip
    directory: "." # Location of package manifests (current directory)
    schedule:
      interval: "weekly" # Update dependencies every week
    ignore:
      - dependency-name: "requests<2.27.0" # Ignore updates to requests<2.27.0
        reason: "Breaking changes in 2.27.0"

